CREATE TABLE Ceps (
    CODIGO INT IDENTITY(1,1) PRIMARY KEY,
    CEP VARCHAR(9) NOT NULL,              
    LOGRADOURO VARCHAR(255),
    COMPLEMENTO VARCHAR(255),
    BAIRRO VARCHAR(100),
    LOCALIDADE VARCHAR(100),
    UF CHAR(2)                    
);